/*

   Big Time watch

   A digital watch with large digits.


   A few things complicate the implementation of this watch:

   a) The largest size of the Nevis font which the Pebble handles
      seems to be ~47 units (points or pixels?). But the size of
      characters we want is ~100 points.

      This requires us to generate and use images instead of
      fonts--which complicates things greatly.

   b) When I started it wasn't possible to load all the images into
      RAM at once--this means we have to load/unload each image when
      we need it. The images are slightly smaller now than they were
      but I figured it would still be pushing it to load them all at
      once, even if they just fit, so I've stuck with the load/unload
      approach.

 */

#include "pebble.h"

static Window *window;

//
// There's only enough memory to load about 6 of 10 required images
// so we have to swap them in & out...
//
// We have one "slot" per digit location on screen.
//
// Because layers can only have one parent we load a digit for each
// slot--even if the digit image is already in another slot.
//
// Slot on-screen layout:
//     0 1
//     2 3
//
#define TOTAL_IMAGE_SLOTS 4

#define NUMBER_OF_IMAGES 10

static int mInvert = 1;			// Invert colours (0/1)
static int mVibeMinutes = 0;	// Vibrate every X minutes

// These images are 72 x 84 pixels (i.e. a quarter of the display),
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_WHITE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_WHITE_0, RESOURCE_ID_IMAGE_NUM_WHITE_1, RESOURCE_ID_IMAGE_NUM_WHITE_2,
  RESOURCE_ID_IMAGE_NUM_WHITE_3, RESOURCE_ID_IMAGE_NUM_WHITE_4, RESOURCE_ID_IMAGE_NUM_WHITE_5,
  RESOURCE_ID_IMAGE_NUM_WHITE_6, RESOURCE_ID_IMAGE_NUM_WHITE_7, RESOURCE_ID_IMAGE_NUM_WHITE_8,
  RESOURCE_ID_IMAGE_NUM_WHITE_9
};

const int IMAGE_RESOURCE_BLACK_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_BLACK_0, RESOURCE_ID_IMAGE_NUM_BLACK_1, RESOURCE_ID_IMAGE_NUM_BLACK_2,
  RESOURCE_ID_IMAGE_NUM_BLACK_3, RESOURCE_ID_IMAGE_NUM_BLACK_4, RESOURCE_ID_IMAGE_NUM_BLACK_5,
  RESOURCE_ID_IMAGE_NUM_BLACK_6, RESOURCE_ID_IMAGE_NUM_BLACK_7, RESOURCE_ID_IMAGE_NUM_BLACK_8,
  RESOURCE_ID_IMAGE_NUM_BLACK_9
};

enum {
    INVERT_KEY = 0x1,
    VIBEMINUTES_KEY = 0x3,
	NUM_CONFIG_KEYS = 0x2
};

static AppSync sync;
static uint8_t sync_buffer[128];

static GBitmap *images[TOTAL_IMAGE_SLOTS];
static BitmapLayer *image_layers[TOTAL_IMAGE_SLOTS];
static InverterLayer* inverter_layer;

#define EMPTY_SLOT -1

// The state is either "empty" or the digit of the image currently in
// the slot--which was going to be used to assist with de-duplication
// but we're not doing that due to the one parent-per-layer
// restriction mentioned above.
static int image_slot_state[TOTAL_IMAGE_SLOTS] = {EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT};

static void load_digit_image_into_slot(int slot_number, int digit_value) {
  /*

     Loads the digit image from the application's resources and
     displays it on-screen in the correct location.

     Each slot is a quarter of the screen.

   */

  // TODO: Signal these error(s)?

  if ((slot_number < 0) || (slot_number >= TOTAL_IMAGE_SLOTS)) {
    return;
  }

  if ((digit_value < 0) || (digit_value > 9)) {
    return;
  }

  if (image_slot_state[slot_number] != EMPTY_SLOT) {
    return;
  }

  image_slot_state[slot_number] = digit_value;
	if (mInvert){
  images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_WHITE_IDS[digit_value]);
}
	if (!mInvert){
		  images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_BLACK_IDS[digit_value]);
	};
	
	GRect frame = (GRect) {
    .origin = { (slot_number % 2) * 72, (slot_number / 2) * 84 },
    .size = images[slot_number]->bounds.size
  };
  BitmapLayer *bitmap_layer = bitmap_layer_create(frame);
  image_layers[slot_number] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, images[slot_number]);
  Layer *window_layer = window_get_root_layer(window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));
}

static void unload_digit_image_from_slot(int slot_number) {
  /*

     Removes the digit from the display and unloads the image resource
     to free up RAM.

     Can handle being called on an already empty slot.

   */

  if (image_slot_state[slot_number] != EMPTY_SLOT) {
    layer_remove_from_parent(bitmap_layer_get_layer(image_layers[slot_number]));
    bitmap_layer_destroy(image_layers[slot_number]);
    gbitmap_destroy(images[slot_number]);
    image_slot_state[slot_number] = EMPTY_SLOT;
  }

}

static void display_value(unsigned short value, unsigned short row_number, bool show_first_leading_zero) {
  /*

     Displays a numeric value between 0 and 99 on screen.

     Rows are ordered on screen as:

       Row 0
       Row 1

     Includes optional blanking of first leading zero,
     i.e. displays ' 0' rather than '00'.

   */
  value = value % 100; // Maximum of two digits per row.

  // Column order is: | Column 0 | Column 1 |
  // (We process the columns in reverse order because that makes
  // extracting the digits from the value easier.)
  for (int column_number = 1; column_number >= 0; column_number--) {
    int slot_number = (row_number * 2) + column_number;
    unload_digit_image_from_slot(slot_number);
    if (!((value == 0) && (column_number == 0) && !show_first_leading_zero)) {
      load_digit_image_into_slot(slot_number, value % 10);
    }
    value = value / 10;
  }
}

static unsigned short get_display_hour(unsigned short hour) {

  if (clock_is_24h_style()) {
    return hour;
  }

  unsigned short display_hour = hour % 12;

  // Converts "0" to "12"
  return display_hour ? display_hour : 12;

}

static void display_time(struct tm *tick_time) {

  // TODO: Use `units_changed` and more intelligence to reduce
  //       redundant digit unload/load?

  display_value(get_display_hour(tick_time->tm_hour), 0, false);
  display_value(tick_time->tm_min, 1, true);
}

static void handle_minute_tick(struct tm *tick_time, TimeUnits units_changed) {
  display_time(tick_time);
	//if (vibrate != vibrate_none) {
		if ((tick_time->tm_min % mVibeMinutes == 0 ) && (tick_time->tm_sec==0))
		{
			vibes_double_pulse();	
		}
	//}
}

static void sync_tuple_changed_callback(const uint32_t key, const Tuple * new_tuple, const Tuple * old_tuple, void *context) {
    // APP_LOG(APP_LOG_LEVEL_DEBUG, "TUPLE! %lu : %d", key, new_tuple->value->uint8);
	if(new_tuple==NULL || new_tuple->value==NULL) {
		return;
	}
    switch (key) {

		case INVERT_KEY:
			//remove_invert();
			mInvert = new_tuple->value->uint8;
		    window_set_background_color(window, (mInvert) ? GColorBlack : GColorWhite);
             // swap colours now.
             time_t now = time(NULL);
             struct tm *tick_time = localtime(&now);
             display_time(tick_time);
			//if (mInvert) {
			//	set_invert();
			//}
			break;

		case VIBEMINUTES_KEY:
			mVibeMinutes = new_tuple->value->int32;
		/* TODO: Handle >59 minutes vibe
		    if(mVibeMinutes>59) {
			    mVibeMinutes -= 60;
            }
		*/

			break;


	}
}



static void init() {

	Tuplet initial_values[NUM_CONFIG_KEYS] = {
		TupletInteger(INVERT_KEY, mInvert),
		TupletInteger(VIBEMINUTES_KEY, mVibeMinutes)
	};

	app_message_open(128, 128);
	app_sync_init(&sync, sync_buffer, sizeof(sync_buffer), initial_values,
			ARRAY_LENGTH(initial_values), sync_tuple_changed_callback, NULL, NULL);
	
  window = window_create();
  window_stack_push(window, true);
  window_set_background_color(window, (mInvert) ? GColorBlack : GColorWhite);
  //window_set_background_color(window, GColorBlack);
  //  default settings

  // Avoids a blank screen on watch start.
  time_t now = time(NULL);
  struct tm *tick_time = localtime(&now);
  display_time(tick_time);
	
  tick_timer_service_subscribe(MINUTE_UNIT, handle_minute_tick);
}

static void deinit() {
   app_sync_deinit(&sync);
	
  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    unload_digit_image_from_slot(i);
  }
  //  inverter
  inverter_layer_destroy(inverter_layer);
  window_destroy(window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
